services:
  # Backend API Service
  api:
    build:
      context: .. 
      dockerfile: deployments/backend.Dockerfile
    image: retail-engine:latest
    container_name: retail_api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    # environment: 
    #   - REDIS_URL will be pulled from your .env or Render secrets
    restart: unless-stopped
    volumes:
      - reports_data:/app/mlops/reports

networks:
  default:
    name: retail_network

volumes:
  reports_data: