"""add_metadata_tables

Revision ID: 52ce65d336a9
Revises: 93352a8f894b
Create Date: 2026-02-26 12:31:53.511237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ce65d336a9'
down_revision: Union[str, Sequence[str], None] = '93352a8f894b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aisles',
    sa.Column('aisle_id', sa.Integer(), nullable=False),
    sa.Column('aisle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('aisle_id')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_foreign_key(None, 'products', 'departments', ['department_id'], ['department_id'])
    op.create_foreign_key(None, 'products', 'aisles', ['aisle_id'], ['aisle_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_table('departments')
    op.drop_table('aisles')
    # ### end Alembic commands ###
